README.md

Probably a typo. `getName()` returns just string `"From:"`

getPersonName

---

src/Stream/CharsetStreamFilter.php

Hi @tivnet --
Would you mind giving this branch a try?  According to this post: https://bugs.python.org/issue18624 8859-8-I should work the same as 8859-8 for conversion purposes.  Unfortunately I don't have an example 8859-8-I real encoded string to test with, and couldn't find one I know to be a reliable example.
There are probably many others that will need to be added as well.  From the python bug report page which introduces a patch to their aliases file, I found http://python.ca/nas/python/sap-25/Lib/encodings/aliases.py which contains many more candidates :).  I'll have to spend some time with that and see which of those apply and are needed for MMP.
Thanks,
Zaahid

Fix CharsetStreamFilter breaking on unsupported CS

---

src/Stream/Helper/CharsetConverter.php

Hi zbateson,
First of all thank you for MailParser as we've been using for a while at it does its job really well 👍 
Yesterday we came across with the following issue when parsing an incoming email:
`Notice: iconv(): Wrong charset, conversion from WE8MSWIN1252 to UTF-8//TRANSLIT//IGNORE`
It resulted as an html content empty.
We made our way by adding the mime charset as an alias to WINDOWS-1252 and it worked.
Right now we are doing like so:
```
CharsetConverter::$mbAliases['WE8MSWIN1252'] = 'WINDOWS-1252';
$email_parser     = new MailMimeParser();
```
I've made a PR for you to consider adding this alias.
Thanks !

Adding WE8MSWIN1252 alias from WINDOWS-1252.

---

src/MimePart.php

Sometimes the handle could be something other than null but still fail to close. I was getting an unknown  resource which passed the null check but outputs a warning on close.

better check for when to close the resource

---

src/Header/Consumer/QuotedStringConsumer.php
src/Message/Part/ParentHeaderPart.php

I think this should say "@param string ..." in these two places.

Fix @param declaration in PhpDoc (string instead of type)

---

.gitattributes

.gitattributes to make the dist package smaller

---

src/Header/Consumer/Received/GenericReceivedConsumer.php

Since `\A` cannot be repeated, it cannot be contained in a group which characters can be repeated.

Rewritten regex to fix PHP7.3 bug in preg_split()

---

src/Header/Consumer/AbstractConsumer.php

Changed SplFixedArray::fromArray to new ArrayIterator for PHP 8.0
* Unit tested on 7.1 and higher
* My editor removes trailing spaces, but I think that is correct.

PHP 8.0 support

---

src/Header/DateHeader.php

Just a convenience method - useful, when you save this to a `datetime_immutable` database field (i.e. the setter expects `\DateTimeImmutable`)

Added getDateTimeImmutable()

---

src/Message/Part/ParentHeaderPart.php

Add missing nullable return type annotation to ParentHeaderPart::getHeader()

Add missing nullable return type annotation

---

.github/workflows/tests.yml
tests/phpunit.xml

Opened in draft as a test is failing. I haven't figured out what changed in 8.1 for this to happen. I know html encoding and decoding functions handle single quotes differently in 8.1, but I don't think they are used anywhere?
Fyi, it's the first `'` in `'﻿这也不会,那也不会'` that is different.
While searching for a solution on this, I quickly tried to migrate zbateson/mb-wrapper to Github Actions, but for some reason that's not working as suspected. Feel free to fix or just close that PR: https://github.com/zbateson/mb-wrapper/pull/5

Add support for PHP 8.1

---

src/Message/MessagePart.php
src/Message/PartChildrenContainer.php
src/Message/PartHeaderContainer.php
src/Parser/Part/ParserPartStreamContainer.php
src/Stream/MessagePartStream.php

PHP 8.1 expects return types to be correctly specified and match the parent class.  Missing and mismatched return types are now a depreciated feature. This PR makes sure PHP 8.1 does not emit warnings on missing or mismatched return type.
#[\ReturnTypeWillChange] is an official attribute in 8.1 and comment in previous versions, so this should not be an issue for all versions.
Unfortunately PHP 8.2 or 8.3 will probably matching return types, so that means supporting anything less than 7.1 will not be possible. At this point, 7.0 and lower have about 2% share according to Packagist.org, so dropping support for 7.0 and lower would probably not have a big impact on users.  They can still use the older versions.

Adding #[\ReturnTypeWillChange] for PHP8.1 compatibility

---

src/Header/Part/MimeLiteralPart.php
tests/MailMimeParser/Header/Part/MimeLiteralPartTest.php

Fix issue https://github.com/zbateson/mail-mime-parser/issues/160

Fix: empty utf8 quoted not parsed correctly

---

src/IMessage.php

Currently the comment and signature of `IMessage::setHtmlPart` is
```php
/**
* [...]
* @param string $contentTypeCharset the charset to use as the text/html
*        part's content-type header charset value.
*/
public function setHtmlPart($resource, $charset = 'UTF-8');
```
Symfony's DeprecationErrorHandler thinks that in the next main version of the package there will be a new parameter for this function:
> Remaining indirect deprecation notices (1)
> 
>  1x: The "ZBateson\MailMimeParser\Message::setHtmlPart()" method will require a new "string $contentTypeCharset" argument in the next major version of its interface "ZBateson\MailMimeParser\IMessage", not defining it is deprecated.
So I propose to change the parameter's name in the interface according to the name in the php doc.

Fix parameter name of IMessage::setHtmlPart according to docComment

---

src/Stream/HeaderStream.php

Still missing in HeaderStream.
Got following message in our unit testing code:
```
PHP Deprecated:  Return type of ZBateson\MailMimeParser\Stream\HeaderStream::update(SplSubject $subject) should either be compatible with SplObserver::update(SplSubject $subject): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/mobilityshop-api/mobilityshop-api/vendor/zbateson/mail-mime-parser/src/Stream/HeaderStream.php on line 51
```

Fix PHP 8.1 return type deprecation notices

---

src/Message/MimePart.php

`MimePart::getContentType()` applies `strtolower()` on the result of `getHeaderValue()`. However, this result can be `null` even though the default value is provided as the default value is not used if the header is present but empty:
```
Content-Type:
```
In such cases, the result is `null` and PHP 8.1 complains:
```
strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
```
My fix applies the default value even if the header is present but empty as in the example above.

Fixed null to string warnings in MimePart->getContentType()

---

README.md

@zbateson Thank you for a very useful package!
This pull request fixes a minor error in the README.md example to get the person name from the TO header.

Fix: README.md example to get person name from TO header

---

src/IMessage.php

The docblock was likely copied and edited from the IMessage::getTextPart() method, but 1 reference was forgotten to be modified.

Fix typo in the IMessage::getHtmlPart() docblock

---

src/Container.php
src/Message/PartChildrenContainer.php

Fixed the following two deprecation messages, which are reported by Symfony's deprecation helper:
>   1x: Method "Pimple\Container::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in child class "ZBateson\MailMimeParser\Container" now to avoid errors or add an explicit @return annotation to suppress this message.
> 
>  1x: Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\PartChildrenContainer" now to avoid errors or add an explicit @return annotation to suppress this message.
The return annotations were already added by #197, but reverted again with commit c1c4b6857cc35ca4b3be19e17d86a811d9296619 (PHPCSFixer).

Fixed some deprecation messages

---

src/di_config.php

This PR makes the library fully PSR-4 compliant.
The [php-di/php-di](https://packagist.org/packages/php-di/php-di) library supports global functions for various setup configurations.  The problem is global functions are not PRS-4 compliant, so using a [super fast and minimal memory footprint autoloader](https://blog.phpfui.com/benchmarking-php-autoloaders) fails.
The solution is simple, use the corresponding classes called by the [global functions](https://github.com/PHP-DI/PHP-DI/blob/master/src/functions.php).  It turns out the php-di library does not use these global functions, and it is considered bad form to use global functions, as they are not PSR-4 compliant. Guzzle has recently depreciated [global functions](https://github.com/guzzle/guzzle/blob/7.8/src/functions.php) for …

Replace global DI library functions with corresponding objects for PRS-4 compliance

---

usage-guide-2.0.md

- Use looped variable.
- `ZBateson\MailMimeParser\Header\Part\AddressPart` class does not have a method `getPersonName()`, `getName()` should be used instead.

Update basic example
